### ISSUE TITLE
About the AUPR calculation

### ISSUE THREAD

**Issue by SakuraRiven** [YifanDengWHU/DDIMDL#1]
Hi, thanks for your share. I have a question about the  AUPR calculation.

In your code, the AUPR is
```
precision, recall, pr_thresholds = precision_recall_curve(y_true, y_score)
return auc(precision, recall, reorder=True)
```
However, the usage in my opinion is
```
precision, recall, pr_thresholds = precision_recall_curve(y_true, y_score)
return auc(recall, precision)
```
The results of these two calculations are different. Would you like to check the calculation?

**Comment by YifanDengWHU** [comment]
Hi, thanks for your careful inspection. Yeah, you are right. I just looked up in Machine Learning by Zhihua Zhou. And it is true that the recall is the x axis and the precision is the y axis.
As for the difference, I examined the code of auc. And tried an example.
>a=[0.1,0.2]
    b=[0.15,0.25]
    c=auc(a,b)
    d=auc(b,a)
>
c=0.02 and d=0.015
For c, it is caculated by (0.15+0.25)*0.1/2=0.02. For d, it is caculated by (0.1+0.2)*0.1/2=0.015. (It calculates the area surrounded by these points in deed.)
It doesn't influence the result a lot, I think, since we are using the same calculation way for different methods. You can correct them in your own work.

**Comment by SakuraRiven** [comment]
Actually, the difference may be obvious ... 15 vs 20 ...

While the recall is monotonous, the precision is often unstable, which is the reason why the ```reorder=True``` is needed in ```auc(precision, recall, reorder=True)```.  You can simply replace the model prediction with random numbers and check the difference.

Emmm, if the difference is obvious, would you like to share the new AUPR in this repo?

**Comment by YifanDengWHU** [comment]
Yes, the difference may be obvious when there are few points. While for the experiments, the correct calculation way seems to improve around 0.02 for each method, so the comparison result isn't influenced a lot.
I have changed
>return auc(precision, recall, reorder=True)
>
into
>return auc(recall, precision, reorder=True)
>
in the repo.

**Comment by SakuraRiven** [comment]
Emmmm, if you do not mind the fairness I would still use the baseline performances for comparison. That's OK?

**Comment by YifanDengWHU** [comment]
No matter it is precision first or recall first, but be sure that they are the same for each model, and it will be OK.
